package com.rijads.easycrawl.init;

import com.rijads.easycrawl.model.ProductRegistry;
import com.rijads.easycrawl.repository.ProductRegistryRepository;
import com.rijads.easycrawl.utility.ProductTextProcessor;
import jakarta.transaction.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class RegistryInitService {
    private static final Logger logger = LoggerFactory.getLogger(RegistryInitService.class);

    private final ProductRegistryRepository registryRepository;
    private final ProductTextProcessor textProcessor;
    
    public RegistryInitService(
            ProductRegistryRepository registryRepository,
            ProductTextProcessor textProcessor) {
        this.registryRepository = registryRepository;
        this.textProcessor = textProcessor;
    }

    @EventListener(ApplicationReadyEvent.class)
    @Transactional
    public void initializeRegistry() {
        logger.info("Checking if registry initialization is needed");
        if (registryRepository.count() > 0) {
            logger.info("Registry already contains data, skipping initialization");
            return;
        }

        logger.info("Initializing product registry with default values");

        List<ProductRegistry> registries = new ArrayList<>();

        // Add known brands
        String[] brands = {
            "3m",
            "a.g. healing",
            "acer",
            "adinstruments",
            "aerodreams",
            "aigo",
            "aiwa",
            "alba",
            "alcatel",
            "alfa",
            "alienware",
            "allied telesis",
            "almaz",
            "alpine",
            "amalgamated wireless",
            "amazon",
            "amd",
            "amkette",
            "amoi",
            "amstrad",
            "analog devices",
            "angstrem",
            "aoc",
            "aopen",
            "apple",
            "arçelik",
            "aselsan",
            "asus",
            "atari",
            "audiovox",
            "avaya",
            "averatec",
            "avibras",
            "axioo",
            "bae systems",
            "beetel",
            "beko",
            "benq",
            "binatone",
            "blackmagic design",
            "blaupunkt",
            "bmtf",
            "bolva",
            "bosch",
            "bose",
            "bpl",
            "braun",
            "brionvega",
            "brondi",
            "brother industries",
            "bt",
            "buffalo",
            "bush",
            "butterfly group",
            "byd electronic",
            "canon",
            "canovate",
            "casio",
            "cea technologies",
            "celkon",
            "changhong",
            "cherry mobile",
            "cicaré",
            "cinemeccanica",
            "cisco systems",
            "citefa",
            "clarinox",
            "clarion",
            "codan",
            "cowon",
            "creative",
            "crucial technology",
            "dawlance",
            "dell",
            "doel",
            "dog & bone",
            "dynalite",
            "dyson",
            "eclipse",
            "ecs",
            "eizo",
            "ekta",
            "electrolux",
            "elsa",
            "emachines",
            "embraer",
            "emerson electric",
            "emerson radio",
            "emi",
            "epox",
            "epson",
            "ericsson",
            "eurotech",
            "fadea",
            "fair group",
            "fairlight",
            "ferranti",
            "fitbit",
            "foxconn",
            "fuji electric",
            "fuji xerox",
            "fujifilm",
            "fujitsu",
            "fukuda inc.",
            "funai",
            "gateway",
            "geliyoo",
            "general satellite",
            "gigabyte",
            "gigaset",
            "gionee",
            "godrej",
            "google",
            "gorenje",
            "gradiente",
            "grundig",
            "haier",
            "hansol",
            "hasee",
            "havells",
            "hcl",
            "hewlett",
            "hidis",
            "hisense",
            "hitachi",
            "hp",
            "htc",
            "huawei",
            "husqvarna",
            "hyundai",
            "iball",
            "ibm",
            "iiyama",
            "indumil",
            "intel",
            "intex",
            "invap",
            "iriver",
            "itautec",
            "jamuna",
            "jbl",
            "jvc",
            "karbonn",
            "kef",
            "kenwood",
            "kingston",
            "končar group",
            "kongsberg gruppen",
            "konica minolta",
            "konka group",
            "koss",
            "kyocera",
            "lanix",
            "lenovo",
            "lg",
            "lite",
            "loewe ag",
            "luxafor",
            "maadiran group",
            "mabe",
            "magnavox",
            "marantz",
            "marcel",
            "marconi",
            "marshall",
            "maspion",
            "mcst",
            "mectron",
            "mediatek",
            "medion",
            "meebox",
            "meizu",
            "metz",
            "micromax",
            "micron technology",
            "microsoft",
            "miele",
            "minister",
            "mitchell & brown",
            "mitsubishi",
            "morphy richards",
            "moser baer",
            "motorola",
            "msi",
            "national",
            "nec",
            "nexian",
            "nikon",
            "ningbo bird",
            "nintendo",
            "nokia",
            "nordic semiconductor",
            "nostromo",
            "notion ink",
            "npo",
            "digital television systems",
            "nvidia",
            "oki",
            "olivetti",
            "olympus",
            "oneplus",
            "onida",
            "oppo",
            "orion",
            "pace",
            "packard bell",
            "pakistan aeronautical complex",
            "panasonic",
            "panda",
            "pantech",
            "pel",
            "pensonic",
            "pentax",
            "philips",
            "pioneer",
            "plantronics",
            "polycom",
            "positivo informatica",
            "powerlab",
            "proscenic",
            "pure",
            "pye",
            "qmobile",
            "qualcomm",
            "radio marconi",
            "radio rentals",
            "rangs",
            "rca",
            "realme",
            "realtek",
            "renesas",
            "revox",
            "ricoh",
            "røde microphones",
            "rovercomputers",
            "russell hobbs",
            "samart",
            "samsung",
            "sandisk",
            "sansui electric",
            "sanyo",
            "satmex",
            "seagate",
            "sega corporation",
            "sennheiser",
            "severin elektro",
            "sgi",
            "sharp",
            "siemens",
            "sii",
            "silicon power",
            "simmtronics",
            "sinclair ",
            "siragon",
            "sitronics",
            "skyworth",
            "snk",
            "snowa",
            "sonos",
            "sony",
            "soyo",
            "sozvezdie",
            "starmobile",
            "sterlite",
            "summit electric supply",
            "sun microsystems",
            "surya",
            "surya roshni",
            "tcl",
            "tdk",
            "technisat",
            "telectronics",
            "telefunken",
            "termozeta",
            "texas instruments",
            "texet",
            "thomson broadcast",
            "thorn",
            "toshiba",
            "tp",
            "transcend",
            "transcom",
            "true",
            "trust",
            "tsmc",
            "uniross",
            "unisonic",
            "unisys",
            "vax",
            "vestel",
            "via",
            "videocon",
            "videotex",
            "videoton",
            "viewsonic",
            "vit",
            "vix",
            "vizio",
            "voltas",
            "walton",
            "weg industries",
            "western digital",
            "wd",
            "westinghouse",
            "wi",
            "winradio",
            "wipro",
            "wortmann",
            "xerox",
            "xiaomi",
            "yota",
            "zenith",
            "zonda",
            "zopo",
            "zte",
            "zyrex",
            "cat",
            "ulephone",
            "nothing"
        };

        for (String brand : brands) {
            registries.add(
                    createRegistry(
                            ProductRegistry.RegistryType.BRAND,
                            brand,
                            null,
                            "Common brand: " + brand));
        }

        // Add common words to ignore
        String[] commonWords = {
            "new",
            "the",
            "best",
            "original",
            "genuine",
            "official",
            "premium",
            "super",
            "mega",
            "sale",
            "hot",
            "deal",
            "free",
            "shipping",
            "authentic",
            "ultimate",
            "enhanced",
            "advanced",
            "innovative",
            "revolutionary",
            "high-quality",
            "luxury",
            "elite",
            "classic",
            "modern",
            "upgraded",
            "improved",
            "latest",
            "top-rated",
            "bestselling",
            "fast",
            "instant",
            "quick",
            "easy",
            "convenient",
            "lightweight",
            "affordable",
            "value",
            "budget",
            "pure",
            "specialized",
            "expert",
            "essential",
            "must-have",
            "trending",
            "popular",
            "rated",
            "reviewed",
            "approved",
            "tested",
            "guaranteed",
            "satisfaction",
            "clearance",
            "discount",
            "bargain",
            "bonus",
            "gift",
            "perfect",
            "complete",
            "full",
            "mobitel",
            "preklopni",
            "smartphone"
        };

        for (String word : commonWords) {
            registries.add(
                    createRegistry(
                            ProductRegistry.RegistryType.COMMON_WORD,
                            word,
                            null,
                            "Common word to ignore"));
        }

        // Add colors
        String[] colors = {
            "black",
            "white",
            "red",
            "blue",
            "green",
            "yellow",
            "pink",
            "purple",
            "gray",
            "grey",
            "silver",
            "gold",
            "orange",
            "brown",
            "navy",
            "teal",
            "aqua",
            "turquoise",
            "indigo",
            "violet",
            "magenta",
            "maroon",
            "crimson",
            "scarlet",
            "burgundy",
            "ruby",
            "emerald",
            "jade",
            "forest",
            "olive",
            "lime",
            "mint",
            "sage",
            "seafoam",
            "azure",
            "cobalt",
            "sapphire",
            "cerulean",
            "sky",
            "royal",
            "electric",
            "midnight",
            "steel",
            "slate",
            "charcoal",
            "onyx",
            "ebony",
            "ivory",
            "cream",
            "beige",
            "tan",
            "khaki",
            "taupe",
            "sand",
            "desert",
            "caramel",
            "bronze",
            "copper",
            "rust",
            "amber",
            "honey",
            "champagne",
            "platinum",
            "pewter",
            "gunmetal",
            "chrome",
            "metallic",
            "iridescent",
            "opal",
            "pearl",
            "pearlescent",
            "holographic",
            "matte",
            "glossy",
            "satin",
            "brushed",
            "polished",
            "rose gold",
            "arctic white",
            "jet black",
            "obsidian black",
            "phantom black",
            "space gray",
            "space black",
            "alpine green",
            "pacific blue",
            "sierra blue",
            "deep purple",
            "midnight green",
            "sunset orange",
            "sunrise red",
            "twilight purple",
            "midnight blue",
            "starlight",
            "moonlight",
            "sunburst",
            "stardust",
            "cosmic",
            "galactic",
            "nebula",
            "aurora",
            "northern lights",
            "shadow black",
            "shadow gray",
            "phantom white",
            "mystic bronze",
            "mystic silver",
            "mystic blue",
            "mystic green",
            "frost white",
            "frosted silver",
            "glacier blue",
            "glacier white",
            "ocean blue",
            "ocean green",
            "deep sea blue",
            "tropical green",
            "vintage brown",
            "vintage gold",
            "vintage copper",
            "antique brass",
            "antique gold",
            "rustic brown",
            "military green",
            "army green",
            "camo green",
            "titanium",
            "natural titanium",
            "desert titanium",
            "graphite",
            "carbon",
            "carbon fiber",
            "slate gray",
            "stone gray",
            "pebble gray",
            "ash gray",
            "smoky black",
            "stormy gray",
            "SilverShadow",
            "IcyBlue",
            "HeatWave",
            "VolcanicRed",
            "SunsetGold",
            "MoonlightSilver",
            "ForestMist",
            "OceanDepth",
            "RubyFusion",
            "AmethystGlow",
            "SapphireDusk",
            "EmeraldAura",
            "DesertSand",
            "CrimsonEdge",
            "FrostBite",
            "LavenderDream",
            "MidnightEssence",
            "CoralBlush",
            "TopazShimmer"
        };

        for (String color : colors) {
            registries.add(
                    createRegistry(
                            ProductRegistry.RegistryType.COLOR,
                            color,
                            null,
                            "Common product color"));
        }

        // Add storage patterns
        String[] storagePatterns = {
            "(\\d+\\s*\\+\\s*\\d+\\s*(?:gb|tb|gig|gigs|gigabyte|gigabytes|terabyte|terabytes)(?:\\s+storage)?)",
            "(\\d+\\s*(?:gb|tb|gig|gigs|gigabyte|gigabytes|terabyte|terabytes)(?:\\s+storage)?)",
            "(\\d+\\s*g(?:b)?(?:\\s+storage)?)",
            "((?:storage|capacity|memory):\\s*\\d+\\s*(?:gb|tb|g))",
            "(\\d+\\s*(?:gb|tb)\\s*(?:ssd|hdd|nvme|storage|drive))",
            "(\\d+\\s*(?:mb|kb)\\s*(?:ram|memory|cache))"
        };

        for (String pattern : storagePatterns) {
            registries.add(
                    createRegistry(
                            ProductRegistry.RegistryType.STORAGE_PATTERN,
                            pattern,
                            null,
                            "Regex pattern for storage capacity extraction"));
        }

        registryRepository.saveAll(registries);
        logger.info("Initialized registry with {} entries", registries.size());

        // Refresh the text processor cache
        textProcessor.refreshRegistry();
    }

    private ProductRegistry createRegistry(
            ProductRegistry.RegistryType type, String key, String value, String description) {

        ProductRegistry registry = new ProductRegistry();
        registry.setRegistryType(type);
        registry.setRegistryKey(key);
        registry.setRegistryValue(value);
        registry.setDescription(description);
        registry.setEnabled(true);

        return registry;
    }
}
